var roa = ["roa", "roa.", "roa!", "roa?"];
var roaR = ["How are you enjoying your DLC?", "Like Smash Bros. but for hipsters.", "When you can't afford a ledge mechanic.", "When you're more poor than even Smash Bros. players.", "That ain't Falco.", "Like Smash Bros. but generic and off-brand.", "That's not a fighting game."];

var arena = ["s1", "s2", "sg", "s3", "s3fb", "s4", "sr", "nsuns", "nsuns2", "nsuns3", "nsuns4", "nsunsg", "nsunsr", "uns", "uns1", "uns2", "uns3", "uns4", "unsg", "unsr", "nuns", "nuns1", "nuns2", "nuns3", "nuns4", "nunsg", "nunsr", "opbb", "ssss", "mhaoj", "zbmb", "zbmf", "nsuns!", "nsuns2!", "nsuns3!", "nsuns4!", "nsunsg!", "nsunsr!", "uns!", "uns1!", "uns2!", "uns3!", "uns4!", "unsg!", "unsr!", "nuns!", "nuns1!", "nuns2!", "nuns3!", "nuns4!", "nunsg!", "nunsr!", "opbb!", "ssss!", "mhaoj!", "zbmb!", "zbmf!", "nsuns.", "nsuns2.", "nsuns3.", "nsuns4.", "nsunsg.", "nsunsr.", "uns.", "uns1.", "uns2.", "uns3.", "uns4.", "unsg.", "unsr.", "nuns.", "nuns1.", "nuns2.", "nuns3.", "nuns4.", "nunsg.", "nunsr.", "opbb.", "ssss.", "mhaoj.", "zbmb.", "zbmf.", "nsuns?", "nsuns2?", "nsuns3?", "nsuns4?", "nsunsg?", "nsunsr?", "uns?", "uns1?", "uns2?", "uns3?", "uns4?", "unsg?", "unsr?", "nuns?", "nuns1?", "nuns2?", "nuns3?", "nuns4?", "nunsg?", "nunsr?", "opbb?", "ssss?", "mhaoj?", "zbmb?", "zbmf?", "skev", "sksv", "skev!", "sksv!", "skev.", "sksv.", "skev?", "sksv?", "klkif", "klkif.", "klkif?", "klkif!"];
var arenaR = ["Literally everyone in that game plays the exact same.", "Don't even lie, you play this game for the waifus.", "That isn't a fighting game.", "You literally only press one button in that game.", "Only scrubs play that game.", "Only filthy casuals play that game.", "That game isn't worth anyone's time, it's not even competitive.", "Mario Party is more competitive than that game.", "Literally nobody plays that game.", "That game has the worst mechanics ever made.", "That's the most jank game ever, why would anyone play that?", "Oh yeah, that open-world beat em up game!", "God, that game has the most toxic fanbase of weeaboos out there.", "Only shills and fanboys buy these shitty, overly mediocre anime games.", "Only shills and fanboys defend these shitty, overly mediocre anime games."];

var pokken = ["pokken", "pokken!", "pokken.", "pokken?"];
var pokkenR = ["Literally everyone in that game plays the exact same.", "Pokken is so unknown, even my creator forgot to put it in until someone mentioned it!", "Isn't it like that Ninja Storm game or something?", "Isn't this just a Tekken clone with weird fetish animals?", "The developers couldn't even decide whether they wanted a casual beat 'em up or an even more casual beat 'em up, so they put both in the game.", "You have to be really into Pokemon to even touch Pokken.", "How's the community of 8 people?", "I think everyone jumped off the Pokken ship when MattPatt was selected to go to a tournament over actual Pokken players.", "At least my Pokken pad is great for playing everything except Pokken!", "Only furries play this game.", "Only Nintendrones play this game.", "They thought the reason it sold poorly was because it was on Wii U. How funny, it sold poorly on Switch as well.", "That isn't a fighting game.", "You literally only press one button in that game.", "Only scrubs play that game.", "Only filthy casuals play that game.", "That game isn't worth anyone's time, it's not even competitive.", "Mario Party is more competitive than that game.", "Literally nobody plays that game.", "That game has the worst mechanics ever made.", "That's the most jank game ever, why would anyone play that?", "Oh yeah, that open-world beat em up game!"];

module.exports = { roa, roaR, arena, arenaR, pokken, pokkenR };
