var snk = ["snk", "snk.", "snk!", "snk?"];
var snkR = ["Legends claim that SNK is still on the verge of bankruptcy to this day. They're not wrong.", "The middle-ground between Street Fighter and Marvel VS Capcom.", "When you're too poor to buy Street Fighter.", "Literally the second most dated fighting game.", "Anyone want to play Street Fighter instead?", "Wait, isn't that just M.U.G.E.N. with less content?", "Don't even lie, you play that for waifus.", "Only SNK shills play their games."];

var kof = ["garou", "garou!", "garou.", "garou?", "kof", "kof94", "kof'94", "kof95", "kof'95", "kof96", "kof'96", "kof97", "kof'97", "kof98", "kof'98", "kof99", "kof'99", "kof00", "kof'00", "kof01", "kof'01", "kof02", "kof'02", "kof03", "kof'03", "kofxi", "kof11", "kofxii", "kof12", "kofxiii", "kof13", "kofmi", "kofmi2", "kof.", "kof94.", "kof'94.", "kof95.", "kof'95.", "kof96.", "kof'96.", "kof97.", "kof'97.", "kof98.", "kof'98.", "kof99.", "kof'99.", "kof00.", "kof'00.", "kof01.", "kof'01.", "kof02.", "kof'02.", "kof03.", "kof'03.", "kofxi.", "kof11.", "kofxii.", "kof12.", "kofxiii.", "kof13.", "kofmi.", "kofmi2.", "kof!", "kof94!", "kof'94!", "kof95!", "kof'95!", "kof96!", "kof'96!", "kof97!", "kof'97!", "kof98!", "kof'98!", "kof99!", "kof'99!", "kof00!", "kof'00!", "kof01!", "kof'01!", "kof02!", "kof'02!", "kof03!", "kof'03!", "kofxi!", "kof11!", "kofxii!", "kof12!", "kofxiii!", "kof13!", "kofmi!", "kofmi2!", "kof?", "kof94?", "kof'94?", "kof95?", "kof'95?", "kof96?", "kof'96?", "kof97?", "kof'97?", "kof98?", "kof'98?", "kof99?", "kof'99?", "kof00?", "kof'00?", "kof01?", "kof'01?", "kof02?", "kof'02?", "kof03?", "kof'03?", "kofxi?", "kof11?", "kofxii?", "kof12?", "kofxiii?", "kof13?", "kofmi?", "kofmi2?"];
var kofR = ["There's a community for that game?", "How's the outdated graphics?", "I swear this game is the Final Fantasy of fighting games. And by that I mean there's way too many damn sequels.", "What's the difference between each King of Fighters game? The year on the logo.", "I thought regular delay based was bad enough, but KOF takes the cake with awful netcode."];

var kof14 = ["kofxiv", "kof14", "kofxiv.", "kof14.", "kofxiv!", "kof14!", "kofxiv?", "kof14?"];
var kof14R = ["There's a community for that game?", "PS2 graphics.", "How does it feel to play the game even SNK fans betrayed?", "How was EVO 2018? See any good KOF matches on main stage?", "Even SNK wants to forget KOF14 existed.", "Why play KOF14 when KOF13 exists?", "lol autocombos"];

var samsho = ["shodown", "shodown.", "shodown!", "shodown?"];
var samshoR = ["It feels like I'm playing SF1 when I play SamSho.", "Why does every move do 50% HP damage minimum?", "Even the combo system ran away from SamSho.", "Play a real fighting game.", "Why is the entire game the neutral game?", "Good graphics don't make up for terrible gameplay."];

module.exports = { snk, snkR, kof, kofR, kof14, kof14R, samsho, samshoR };
